### ISSUE TITLE
Create a Wishlist

### ISSUE THREAD

**Issue by HelenZhou2400** [CSCI-GA-2820-FA24-001/wishlists#1]
**As a** customer
**I need** the ability to create a wishlist 
**So that** I can store products that I want to purchase later
   
 ### Details and Assumptions
 * The wishlist will contain a title for the wishlist, owner orcustomer reference, and a list of products
 * Customers can create multiple wishlists with different titles
 * Initially the wishlist will be empty
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a new customer wants to create a list of items for later use
 When the user creates a wishlist, POST /wishlists is called
 Then the list should be saved in database with title, owner reference, and an empty product collection
```

**Comment by asg8830** [comment]
This seems like the most important story and should be priority one

**Comment by HelenZhou2400** [comment]
Unable to connect multiple issues to one PR, this issue is done along with issue#10.
