### ISSUE TITLE
Read an Item from a Wishlist

### ISSUE THREAD

**Issue by Wstz0231** [CSCI-GA-2820-FA24-001/wishlists#7]
**As a** customer
**I need** to view the details of a specific item in my wishlist
**So that** I can review the product information
   
 ### Details and Assumptions
 * Create a REST API to fetch the details of a specific item from a wishlist
 * The client will provide both the wishlist ID and the item ID to fetch the specific item
 * Query the database to retrieve the item details for the provided IDs
 * If the item or wishlist ID does not exist, the system should return an error message
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a customer has a specific wishlist with items
When they send a GET request to "/wishlists/{id}/items/{id}"
Then the service should return the details of the specified item.
```

**Comment by HelenZhou2400** [comment]
Same PR #34 with delete an item
