### ISSUE TITLE
Add UI for Querying Wishlists

### ISSUE THREAD

**Issue by HelenZhou2400** [CSCI-GA-2820-FA24-001/wishlists#70]
**As a** eCommerce manager
**I need** a UI to search for specific wishlists by name, userid, or date_created
**So that** I can filter and retrieve specific wishlists
   
 ### Details and Assumptions
 * The query functionality will allow filtering with following query parameters: name, userid, date_created
 * A search bar will be provided on the list view page.
   
 ### Acceptance Criteria  
   
 ```gherkin
Given the eCommerce manager is on the wishlist list view page  
When they enter a query in the search bar for a wishlist’s name or customer  
Then the list updates to show only the wishlists matching the query  
```

**Comment by yingliu019** [comment]
I pushed this feature change to master branch by mistake. (should create a PR and then merge)

The change is https://github.com/CSCI-GA-2820-FA24-001/wishlists/commit/0144c87233a25cd8174885ed1267c7757fe68f21.
