### ISSUE TITLE
Add Swagger Documentation for API Endpoints

### ISSUE THREAD

**Issue by HelenZhou2400** [CSCI-GA-2820-FA24-001/wishlists#73]
**As a** developer
**I need** to add Swagger annotations to document the REST API
**So that** the API is well-documented and easy to use for other developers or consumers
   
 ### Details and Assumptions
 * Each endpoint should be annotated with Swagger documentation using Flask-RESTX decorators.
 * Swagger documentation should be available at /apidocs/.
 * All request and response data models should be properly defined using Flask-RESTX's api.model.
   
 ### Acceptance Criteria  
   
 ```gherkin
Given the API endpoints are annotated with Swagger documentation  
When a user accesses the `/apidocs/` route  
Then they should see a well-organized, accurate Swagger UI with details of each endpoint, including request/response data models  
```

**Comment by ahighmoon** [comment]
I am currently working on this now.
