### ISSUE TITLE
Create a route to access the microservice

### ISSUE THREAD

**Issue by HelenZhou2400** [CSCI-GA-2820-FA24-001/wishlists#85]
**As a** develoepr
**I need** to create a route to the wishlist service in OpenShift
**So that** the service is accessible externally
   
 ### Details and Assumptions
 * The route will expose the service using an environment variable for BASE_URL.
   
 ### Acceptance Criteria  
   
 ```gherkin
Given a deployed wishlist service in Kubernetes  
When I create a route to the service  
Then the service should be accessible via the defined route  
```

**Comment by yingliu019** [comment]
I think starting from slides 200 has the instruction, just a little bit manual operations and I don't know what kind of code needs to be commit.

name: cd-pipeline
<img width="1381" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjhRQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--91c15a29d5a7dbf58182f036e6ce8103d75b76b2/image.png" alt="image.png" />
