### ISSUE TITLE
Set up a webhook for GitHub repository

### ISSUE THREAD

**Issue by HelenZhou2400** [CSCI-GA-2820-FA24-001/wishlists#87]
**As a** developer
**I need** to configure a WebHook on the GitHub repository
**So that** commits to the master branch trigger the Tekton pipeline
   
 ### Details and Assumptions
 * A team member with admin access will configure the webhook.
 * The webhook will trigger the EventListener to start the pipeline.
   
 ### Acceptance Criteria  
   
 ```gherkin
Given a webhook is configured on the GitHub repository  
When a commit is pushed to the `master` branch  
Then the webhook should trigger the Tekton pipeline to execute  
```

**Comment by yingliu019** [comment]
@ahighmoon Hi Yifei, the instruction starts around the 55m in the video and only the admin is able to do that. So I assign to you for now since you volunteer to demo :)
